const fs=require('fs'),path=require('path'),today=new Date().toISOString().slice(0,10),slug=today;
const feed=JSON.parse(fs.readFileSync(path.join(__dirname,'..','feed.json'),'utf8'));
if(feed.posts.find(p=>p.slug===slug)){console.log('Exists');process.exit(0)}
const pool=[[["根据脸型选发型：圆脸方脸长脸最适合什么发型","圆脸选有层次的中长发拉长脸型。方脸选侧分大波浪软化棱角。长脸选刘海缩短脸型不要中分。","选发型"],["2025年最流行的女生短发：35款清爽短发推荐","锁骨发、一刀切短发、微翘短发、日系少年感短发。短发的好处：洗头吹头只需5分钟。","女生发型"],["烫发后怎么打理：卷发保持半年的秘诀","洗完头发不要搓用毛巾按压吸水、弹力素从下往上抓、吹风机加风罩烘到半干。睡觉用真丝枕巾减少摩擦。","烫发护理"]],[["染发颜色怎么选：显白不踩雷的发色推荐","暖皮选冷调色（灰棕亚麻青）、冷皮选暖调色（蜜茶棕焦糖）。第一次染不要太浅色、选比目标色深一度的。","染发"],["男生发型推荐：根据头型选发型","头型扁的不要剃太短。圆脸适合高层次增加高度。方脸适合纹理烫柔化线条。发量少的选短发看起来多。","男生发型"],["吹风机正确使用方法：吹出理发店的效果","先吹发根再吹发尾、风嘴朝下顺毛鳞片、冷风定型。半干时用圆形梳卷发尾。吹干前抹护发精油防热损伤。","造型技巧"]],[["圆脸女生适合的发型：12款显脸小的发型","齐肩锁骨发+侧分、八字刘海+层次中长发、高马尾拉长脸型。不要齐刘海会让脸更圆。","选发型"],["自己在家染发的完整教程：不翻车的秘诀","染前不洗头头皮油脂保护、分区上色从发尾开始发根最后、停留时间按说明书不要超时。皮肤过敏测试要做。","染发"],["掉头发严重怎么办：脱发原因和日常护理","产后脱发和压力脱发是暂时的会恢复。雄激素脱发是遗传的要用药。洗发水选无硅油的。","护发知识"]],[["刘海怎么打理：不同脸型选不同刘海","圆脸选八字刘海、方脸选侧分刘海、长脸选齐刘海、心形脸选空气刘海。刘海油了用干发喷雾急救。","选发型"],["烫发前必看：冷烫热烫纹理烫的区别","热烫卷度持久适合大卷、冷烫不伤发质适合小卷。纹理烫适合男生自然微卷。沙发发质先做柔顺再烫。","烫发知识"],["发量少的女生怎么办：显发量多的发型和护理","剪高层次蓬松感强、烫纹理增加体积、侧分比中分显多。用蓬松喷雾在发根、不要频繁洗头破坏油脂。","护发知识"]],[["方脸女生适合的发型：柔化面部线条的9款发型","侧分大波浪、长刘海遮颧骨、层次锁骨发。不要贴头皮的发型会暴露方下颌角。","选发型"],["发膜和护发素的区别：多久用一次","护发素每次洗头用闭合毛鳞片、发膜每周1-2次深层滋养。发膜要避开头皮只涂发中和发尾。","护发知识"],["鲨鱼夹怎么夹好看：低马尾丸子头盘发教程","先扎低马尾再扭转发束、用鲨鱼夹夹住扭转处。留两缕鬓角碎发修饰脸型。松一点比紧的好看。","造型教程"]],[["长发女生夏季清爽发型：15款扎发教程","高马尾、低丸子头、半扎发、麻花辫、双丸子、丝巾编发。扎之前用电卷棒稍微卷一下更有纹理感。","造型教程"],["发际线后移怎么办：原因和改善方法","长期扎太紧的头发会导致牵引性脱发。松一点扎、换位置分缝、用生发精华按摩头皮。","护发知识"],["卷发棒怎么用不伤头发：温度和技巧","细软发质160度、正常发质180度、粗硬发质200度。热保护喷雾是必须的。每次不超过10秒。","造型技巧"]],[["长发还是短发：换个发型改变气质","想剪短发的可以先试锁骨发过渡。捐发给癌症患者可以把剪下来的长发捐出去有意义。","选发型"],["白头发能不能拔：关于白发的误区","拔白头发不会让它越长越多但可能损伤毛囊。白发是毛囊黑色素减少的结果可以染发遮盖。","护发知识"],["去理发店怎么和发型师沟通：带图最清楚","不要只说修一点点。带上你想要的发型图+你不想要的图两张对比。说清楚长度到哪个位置。","实用技巧"]],[["扁头怎么选发型：7款后脑勺显饱满的发型","后脑勺做高层次蓬松、扎高马尾或丸子头、用蓬松夹夹后脑勺。不要贴头皮的短发。","选发型"],["自己剪刘海教程：齐刘海和八字刘海","用专业剪刀不要用文具剪刀、干发剪、宁长勿短。对齐眉心开始往两边斜着剪、剪完用卷发棒稍微带一下。","造型技巧"],["为什么你的发型总是不好看：避开这5个坑","不看脸型盲目跟风、染烫一起做太伤发质、不会打理等于白做、和美发师没沟通清楚、舍不得剪分叉发尾。","避坑指南"]]];
const idx=(new Date().getDate()-1)%pool.length,items=pool[idx];
const postTitle=items[0].tag+' | '+today;
feed.posts.unshift({slug,date:today,title:postTitle,items:items.map(i=>({title:i[0],desc:i[1],tag:i[2]}))});
feed.updated=today;
fs.writeFileSync(path.join(__dirname,'..','feed.json'),JSON.stringify(feed,null,2));
const html='<!DOCTYPE html><html lang="zh-CN"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1.0"><title>'+postTitle+'</title><style>*,*::before,*::after{box-sizing:border-box;margin:0;padding:0}:root{--bg:#fafafa;--card:#fff;--text:#1a1a2e;--t2:#666;--accent:#a21caf;--border:#e5e7eb;--r:10px}body{font-family:-apple-system,BlinkMacSystemFont,"Segoe UI","Noto Sans SC",sans-serif;background:var(--bg);color:var(--text);line-height:1.7}.container{max-width:800px;margin:0 auto;padding:0 20px}header{background:var(--card);border-bottom:1px solid var(--border);padding:20px 0;margin-bottom:32px}header a{color:var(--accent);text-decoration:none;font-size:.9rem}header h1{font-size:1.3rem;margin-top:8px}.post{background:var(--card);border:1px solid var(--border);border-radius:var(--r);padding:28px}.post .date{color:var(--t2);font-size:.8rem;margin-bottom:20px}.entry{margin-bottom:24px;padding-bottom:20px;border-bottom:1px solid var(--border)}.entry:last-child{border-bottom:none}.entry h3{font-size:1rem;margin-bottom:4px}.entry p{color:var(--t2);font-size:.9rem}.tag{display:inline-block;font-size:.72rem;padding:2px 8px;border-radius:10px;margin-left:6px;background:var(--bg);color:var(--accent)}footer{text-align:center;padding:32px 20px;color:var(--t2);font-size:.8rem}@media(max-width:600px){.post{padding:18px}}</style></head><body><header><div class="container"><a href="../index.html">← 首页</a><h1>'+postTitle+'</h1></div></header><main class="container"><article class="post"><div class="date">📅 '+today+'</div>'+items.map(i=>'<div class="entry"><h3>'+i[0]+' <span class="tag">'+i[2]+'</span></h3><p>'+i[1]+'</p></div>').join('')+'</article></main><footer><p>每日更新</p></footer></body></html>';
fs.writeFileSync(path.join(__dirname,'..','posts',slug+'.html'),html);
console.log('Generated:',postTitle);
